# Generated by Django 6.0.6 on 2026-06-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash On Delivery'), ('razorpay', 'Razorpay'), ('upi', 'UPI'), ('card', 'Debit / Credit Card')], max_length=20),
        ),
    ]
