# Generated by Django 6.0.2 on 2026-06-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='inch',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Test Product', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='category',
        ),
    ]
